collections:
  - name: netbox.netbox      # For NetBox inventory
    version: "3.22.0"
  - name: community.general  # For Kubespray
    version: "8.0.0"
  - name: ansible.utils
    version: ">=2.10.3"
