---
# ============================================================================
# Kubespray + Morpheus Integration Playbook (SIMPLE VERSION)
# ============================================================================
# Purpose: Deploy Kubernetes cluster and register with Morpheus
# Usage: ansible-playbook deploy_and_register_simple.yml -i inventory/hosts.yml
# ============================================================================

# 1. Standard Kubespray Deployment
#- name: Deploy Kubernetes Cluster
#  import_playbook: cluster.yml

# 2. Custom Morpheus Registration
- name: Register Cluster with Morpheus
  hosts: kube_control_plane[0]
  become: true
  vars:
    morpheus_url: "{{ lookup('env', 'MORPHEUS_URL') | default('https://98.85.233.250', true) }}"
    morpheus_api_token: "{{ lookup('env', 'MORPHEUS_API_TOKEN') | default(morpheus_api_token | default(''), true) }}"
    cluster_name: "{{ morpheus_cluster_name | default('K8s-' + ansible_hostname) }}"
    kubeconfig_path: "/etc/kubernetes/admin.conf"
    
  tasks:
    - name: Display Morpheus Integration Information
      ansible.builtin.debug:
        msg:
          - "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          - "  MORPHEUS CLUSTER REGISTRATION"
          - "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          - "Morpheus URL:    {{ morpheus_url }}"
          - "Cluster Name:    {{ cluster_name }}"
          - "Kubeconfig:      {{ kubeconfig_path }}"
          - "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

    - name: Validate Morpheus API token
      ansible.builtin.fail:
        msg: |
          ❌ ERROR: morpheus_api_token is required!
          
          Set it via:
            export MORPHEUS_API_TOKEN="your-token"
          
          Or pass it with:
            -e "morpheus_api_token=YOUR_TOKEN"
      when: morpheus_api_token is not defined or morpheus_api_token | length == 0

    - name: Wait for Kubernetes API server to be ready
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: 6443
        delay: 10
        timeout: 300
        state: started

    - name: Check if kubeconfig exists
      ansible.builtin.stat:
        path: "{{ kubeconfig_path }}"
      register: kubeconfig_stat

    - name: Fail if kubeconfig not found
      ansible.builtin.fail:
        msg: "Kubeconfig not found at {{ kubeconfig_path }}"
      when: not kubeconfig_stat.stat.exists

    - name: Verify cluster is accessible
      ansible.builtin.command: >
        kubectl --kubeconfig={{ kubeconfig_path }} get nodes
      register: cluster_check
      changed_when: false
      retries: 10
      delay: 30
      until: cluster_check.rc == 0

    - name: Create Service Account for Morpheus
      ansible.builtin.shell: |
        kubectl --kubeconfig={{ kubeconfig_path }} apply -f - <<EOF
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: morpheus-admin
          namespace: kube-system
        EOF
      register: sa_result
      changed_when: "'created' in sa_result.stdout or 'configured' in sa_result.stdout"

    - name: Grant cluster-admin permissions
      ansible.builtin.shell: |
        kubectl --kubeconfig={{ kubeconfig_path }} apply -f - <<EOF
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        metadata:
          name: morpheus-admin-binding
        subjects:
          - kind: ServiceAccount
            name: morpheus-admin
            namespace: kube-system
        roleRef:
          kind: ClusterRole
          name: cluster-admin
          apiGroup: rbac.authorization.k8s.io
        EOF
      register: crb_result
      changed_when: "'created' in crb_result.stdout or 'configured' in crb_result.stdout"

    - name: Create long-lived API token secret
      ansible.builtin.shell: |
        kubectl --kubeconfig={{ kubeconfig_path }} apply -f - <<EOF
        apiVersion: v1
        kind: Secret
        metadata:
          name: morpheus-admin-token
          namespace: kube-system
          annotations:
            kubernetes.io/service-account.name: morpheus-admin
        type: kubernetes.io/service-account-token
        EOF
      register: secret_result
      changed_when: "'created' in secret_result.stdout or 'configured' in secret_result.stdout"

    - name: Wait for token to be generated
      ansible.builtin.pause:
        seconds: 15
        prompt: "Waiting for Kubernetes to generate service account token..."

    - name: Retrieve token from cluster
      ansible.builtin.shell: |
        kubectl --kubeconfig={{ kubeconfig_path }} get secret morpheus-admin-token \
          -n kube-system -o jsonpath='{.data.token}'
      register: token_b64
      changed_when: false
      retries: 10
      delay: 5
      until: token_b64.stdout | length > 0

    - name: Decode service account token
      ansible.builtin.set_fact:
        morpheus_sa_token: "{{ token_b64.stdout | b64decode }}"

    - name: Get CA certificate
      ansible.builtin.shell: |
        kubectl --kubeconfig={{ kubeconfig_path }} get secret morpheus-admin-token \
          -n kube-system -o jsonpath='{.data.ca\.crt}'
      register: ca_cert_b64
      changed_when: false

    - name: Decode CA certificate
      ansible.builtin.set_fact:
        cluster_ca_cert: "{{ ca_cert_b64.stdout | b64decode }}"

    - name: Verify token works
      ansible.builtin.shell: |
        kubectl --kubeconfig={{ kubeconfig_path }} --token="{{ morpheus_sa_token }}" get nodes
      register: token_verify
      changed_when: false

    - name: Get Kubernetes API server endpoint
      ansible.builtin.shell: |
        kubectl --kubeconfig={{ kubeconfig_path }} config view --minify -o jsonpath='{.clusters[0].cluster.server}'
      register: api_server_url
      changed_when: false

    - name: Display cluster information
      ansible.builtin.debug:
        msg:
          - "Cluster API Server: {{ api_server_url.stdout }}"
          - "Service Account: morpheus-admin"
          - "Token generated successfully ({{ morpheus_sa_token | length }} chars)"

    - name: Register cluster with Morpheus API
      ansible.builtin.uri:
        url: "{{ morpheus_url }}/api/clusters"
        method: POST
        headers:
          Authorization: "BEARER {{ morpheus_api_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          cluster:
            name: "{{ cluster_name }}"
            type: "external-kubernetes-cluster"
            site:
              id: "{{ morpheus_group_id | default(1) | int }}"
            cloud:
              id: "{{ morpheus_cloud_id | default(1) | int }}"
            layout:
              id: "{{ morpheus_layout_id | default(4) | int }}" # <--- QUOTES ADDED HERE
            serviceUrl: "{{ api_server_url.stdout }}"
            serviceToken: "{{ morpheus_sa_token }}"
            apiProxy:
              verifySsl: false
            config:
              certificateAuthority: "{{ cluster_ca_cert | default('') }}"
        validate_certs: false
        status_code: [200, 201]
      register: morpheus_response
      delegate_to: localhost
      become: false 
      run_once: true

    - name: Display Morpheus registration result
      ansible.builtin.debug:
        msg:
          - "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          - "  ✅ CLUSTER REGISTERED WITH MORPHEUS"
          - "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          - "Cluster ID: {{ morpheus_response.json.cluster.id | default('N/A') }}"
          - "Cluster Name: {{ cluster_name }}"
          - "Status: {{ morpheus_response.json.cluster.status | default('Registered') }}"
          - "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
      when: morpheus_response is succeeded

    - name: Save cluster credentials to file
      ansible.builtin.copy:
        content: |
          # Morpheus Cluster Registration Details
          # Generated: {{ ansible_date_time.iso8601 }}
          
          Cluster Name: {{ cluster_name }}
          Morpheus URL: {{ morpheus_url }}
          Cluster ID: {{ morpheus_response.json.cluster.id | default('N/A') }}
          
          API Server: {{ api_server_url.stdout }}
          Service Account: morpheus-admin
          Namespace: kube-system
          
          # To manually verify:
          kubectl --token="{{ morpheus_sa_token }}" --server={{ api_server_url.stdout }} --insecure-skip-tls-verify get nodes
        dest: "/tmp/morpheus-cluster-{{ cluster_name }}.txt"
        mode: '0600'
      when: morpheus_response is succeeded

    - name: Display credentials file location
      ansible.builtin.debug:
        msg: "Credentials saved to: /tmp/morpheus-cluster-{{ cluster_name }}.txt"
      when: morpheus_response is succeeded
