---
# ============================================================================
# Kubespray + Morpheus Integration Playbook (SIMPLE VERSION)
# ============================================================================
# Purpose: Deploy Kubernetes cluster and register with Morpheus
# Usage: ansible-playbook deploy_and_register_simple.yml -i inventory/hosts.yml
# ============================================================================

# 1. Standard Kubespray Deployment
#- name: Deploy Kubernetes Cluster
#  import_playbook: cluster.yml

# 2. Custom Morpheus Registration
- name: Register Cluster with Morpheus
  hosts: kube_control_plane[0]
  become: true
  vars:
    morpheus_url: "{{ lookup('env', 'MORPHEUS_URL') | default('https://98.85.233.250', true) }}"
    morpheus_api_token: "{{ lookup('env', 'morpheus_api_token') | default(morpheus_api_token | default(''), true) }}"
    cluster_name: "{{ morpheus_cluster_name | default('K8s-' + ansible_hostname) }}"
    kubeconfig_path: "/etc/kubernetes/admin.conf"
    
  tasks:
    - name: Display Morpheus Integration Information
      ansible.builtin.debug:
        msg:
          - "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          - "  MORPHEUS CLUSTER REGISTRATION"
          - "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          - "Morpheus URL:    {{ morpheus_url }}"
          - "Cluster Name:    {{ cluster_name }}"
          - "Kubeconfig:      {{ kubeconfig_path }}"
          - "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

    - name: Check if kubeconfig exists
      ansible.builtin.stat:
        path: "{{ kubeconfig_path }}"
      register: kubeconfig_stat

    - name: Fail if kubeconfig not found
      ansible.builtin.fail:
        msg: "Kubeconfig not found at {{ kubeconfig_path }}"
      when: not kubeconfig_stat.stat.exists

    - name: Verify cluster is accessible
      ansible.builtin.command: >
        kubectl --kubeconfig={{ kubeconfig_path }} get nodes
      register: cluster_check
      changed_when: false
      retries: 10
      delay: 30
      until: cluster_check.rc == 0

    - name: Create Service Account for Morpheus
      ansible.builtin.shell: |
        kubectl --kubeconfig={{ kubeconfig_path }} apply -f - <<EOF
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: morpheus-admin
          namespace: kube-system
        EOF
      register: sa_result
      changed_when: "'created' in sa_result.stdout or 'configured' in sa_result.stdout"

    - name: Grant cluster-admin permissions
      ansible.builtin.shell: |
        kubectl --kubeconfig={{ kubeconfig_path }} apply -f - <<EOF
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        metadata:
          name: morpheus-admin-binding
        subjects:
          - kind: ServiceAccount
            name: morpheus-admin
            namespace: kube-system
        roleRef:
          kind: ClusterRole
          name: cluster-admin
          apiGroup: rbac.authorization.k8s.io
        EOF
      register: crb_result
      changed_when: "'created' in crb_result.stdout or 'configured' in crb_result.stdout"

    - name: Create long-lived API token secret
      ansible.builtin.shell: |
        kubectl --kubeconfig={{ kubeconfig_path }} apply -f - <<EOF
        apiVersion: v1
        kind: Secret
        metadata:
          name: morpheus-admin-token
          namespace: kube-system
          annotations:
            kubernetes.io/service-account.name: morpheus-admin
        type: kubernetes.io/service-account-token
        EOF
      register: secret_result
      changed_when: "'created' in secret_result.stdout or 'configured' in secret_result.stdout"

    - name: Wait for token to be generated
      ansible.builtin.pause:
        seconds: 15
        prompt: "Waiting for Kubernetes to generate service account token..."

    - name: Retrieve token from cluster
      ansible.builtin.shell: |
        kubectl --kubeconfig={{ kubeconfig_path }} get secret morpheus-admin-token \
          -n kube-system -o jsonpath='{.data.token}'
      register: token_b64
      changed_when: false
      retries: 10
      delay: 5
      until: token_b64.stdout | length > 0

    - name: Decode service account token
      ansible.builtin.set_fact:
        morpheus_sa_token: "{{ token_b64.stdout | b64decode }}"

    - name: Get CA certificate
      ansible.builtin.shell: |
        kubectl --kubeconfig={{ kubeconfig_path }} get secret morpheus-admin-token \
          -n kube-system -o jsonpath='{.data.ca\.crt}'
      register: ca_cert_b64
      changed_when: false

    - name: Decode CA certificate
      ansible.builtin.set_fact:
        cluster_ca_cert: "{{ ca_cert_b64.stdout | b64decode }}"

    - name: Verify token works
      ansible.builtin.shell: |
        kubectl --kubeconfig={{ kubeconfig_path }} --token="{{ morpheus_sa_token }}" get nodes
      register: token_verify
      changed_when: false

    - name: Get Kubernetes API server endpoint
      ansible.builtin.shell: |
        kubectl --kubeconfig={{ kubeconfig_path }} config view --minify -o jsonpath='{.clusters[0].cluster.server}'
      register: api_server_url
      changed_when: false

    - name: Display cluster information
      ansible.builtin.debug:
        msg:
          - "Cluster API Server: {{ api_server_url.stdout }}"
          - "Service Account: morpheus-admin"
          - "Token generated successfully ({{ morpheus_sa_token | length }} chars)"
    - name: Read kubeconfig file from control plane
      ansible.builtin.command: "cat /etc/kubernetes/admin.conf"
      register: kube_config_file
      changed_when: false
      
    - name: Set Morpheus and Kubernetes facts
      ansible.builtin.set_fact:
        kubeconfig: "{{ kube_config_file.stdout | regex_replace('\n', '')  }}"
        
    - name: Register External Cluster
      ansible.builtin.uri:
        url: "{{ morpheus_url }}/api/clusters"
        method: POST
        headers:
          Authorization: "BEARER {{ morpheus_api_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          cluster:
            name: "sample-cluster-manually"
            type: "external-kubernetes-cluster" # Prevents SSH check
            group: { id: 1 }
            layout: { id: 159 }
            cloud: { id: 1 }
            sshKeyPair: { id: 72 }
            #zone: { id: 1 }
            server: # This block is REQUIRED to fix the sshKeyPair error
              name: "sample-cluster-manually"
              plan: 
                code: "external-default" 
                options: {}
              visibility: "private"
              networkDomain: null
              config:
                apiUrl: "https://44.223.72.12:6443"
                apiToken: "{{ morpheus_sa_token }}"
                serviceAccess: "{{ kubeconfig }}"
        validate_certs: false
        status_code: [200, 201]
      when: existing_clusters.json.meta.total == 0
      register: morpheus_response

    - name: Display Morpheus registration result
      ansible.builtin.debug:
        msg:
          - "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          - "  ✅ CLUSTER REGISTERED WITH MORPHEUS"
          - "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          - "Cluster ID: {{ morpheus_response.json.cluster.id | default('N/A') }}"
          - "Cluster Name: {{ cluster_name }}"
          - "Status: {{ morpheus_response.json.cluster.status | default('Registered') }}"
          - "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
      when: morpheus_response is succeeded

    - name: Save cluster credentials to file
      ansible.builtin.copy:
        content: |
          # Morpheus Cluster Registration Details
          # Generated: {{ ansible_date_time.iso8601 }}
          
          Cluster Name: {{ cluster_name }}
          Morpheus URL: {{ morpheus_url }}
          Cluster ID: {{ morpheus_response.json.cluster.id | default('N/A') }}
          
          API Server: {{ api_server_url.stdout }}
          Service Account: morpheus-admin
          Namespace: kube-system
          
          # To manually verify:
          kubectl --token="{{ morpheus_sa_token }}" --server={{ api_server_url.stdout }} --insecure-skip-tls-verify get nodes
        dest: "/tmp/morpheus-cluster-{{ cluster_name }}.txt"
        mode: '0600'
      when: morpheus_response is succeeded

    - name: Display credentials file location
      ansible.builtin.debug:
        msg: "Credentials saved to: /tmp/morpheus-cluster-{{ cluster_name }}.txt"
      when: morpheus_response is succeeded
