# 2. Register the newly created cluster with Morpheus
- name: 2. Register Cluster with Morpheus
  hosts: kube_control_plane[0]
  become: true
  vars:
    # IMPORTANT: Ensure these are set in AWX Extra Vars or Credentials
    morpheus_url: "https://98.85.233.250"
    morpheus_api_token: "{{ morpheus_api_token }}"
    cluster_name: "K8s-{{ ansible_hostname }}"
    k8s_api_host: "https://{{ ansible_host }}:6443"

  tasks:
    - name: Read kubeconfig from vm-1 (The Master Node)
      ansible.builtin.slurp:
        src: "/etc/kubernetes/admin.conf"
      register: remote_kubeconfig

    - name: Create Service Account for Morpheus
      kubernetes.core.k8s:
        host: "{{ k8s_api_host }}"
        kubeconfig: "{{ remote_kubeconfig.content | b64decode | from_yaml }}"
        validate_certs: false
        definition:
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: morpheus-admin
            namespace: kube-system
      delegate_to: localhost

    - name: Grant cluster-admin permissions to Service Account
      kubernetes.core.k8s:
        host: "{{ k8s_api_host }}"
        kubeconfig: "{{ remote_kubeconfig.content | b64decode | from_yaml }}"
        validate_certs: false
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRoleBinding
          metadata:
            name: morpheus-admin-binding
          subjects:
          - kind: ServiceAccount
            name: morpheus-admin
            namespace: kube-system
          roleRef:
            kind: ClusterRole
            name: cluster-admin
            apiGroup: rbac.authorization.k8s.io
      delegate_to: localhost

    - name: Create long-lived API token secret
      kubernetes.core.k8s:
        host: "{{ k8s_api_host }}"
        kubeconfig: "{{ remote_kubeconfig.content | b64decode | from_yaml }}"
        validate_certs: false
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: morpheus-admin-token
            namespace: kube-system
            annotations:
              kubernetes.io/service-account.name: morpheus-admin
          type: kubernetes.io/service-account-token
      delegate_to: localhost

    - name: Retrieve the Service Account token
      kubernetes.core.k8s_info:
        host: "{{ k8s_api_host }}"
        kubeconfig: "{{ remote_kubeconfig.content | b64decode | from_yaml }}"
        validate_certs: false
        kind: Secret
        name: morpheus-admin-token
        namespace: kube-system
      register: sa_secret
      delegate_to: localhost
      no_log: true

    - name: Post Cluster Details to Morpheus API
      uri:
        url: "{{ morpheus_url }}/api/clusters"
        method: POST
        headers:
          Authorization: "BEARER {{ morpheus_api_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          cluster:
            name: "{{ cluster_name }}"
            type: "kubernetes"
            serviceUrl: "{{ k8s_api_host }}"
            # Decode the base64 token from the secret
            serviceToken: "{{ sa_secret.resources[0].data.token | b64decode }}"
            apiProxy: { verifySsl: false }
        status_code: 201
      delegate_to: localhost
      register: morpheus_response

    - name: Success Message
      debug:
        msg: "Cluster successfully registered! Morpheus ID: {{ morpheus_response.json.cluster.id }}"
      when: morpheus_response.status == 201
