---
# ------------------------------------------------------------
# 1. Standard Kubespray Deployment
# ------------------------------------------------------------
- name: Deploy Kubernetes Cluster
  import_playbook: playbooks/cluster.yml


# ------------------------------------------------------------
# 2. Register Cluster with Morpheus
# ------------------------------------------------------------
- name: Register Cluster with Morpheus
  hosts: kube_control_plane[0]
  become: true
  gather_facts: true

  vars:
    morpheus_url: "https://98.85.233.250"
    morpheus_api_token: "{{ morpheus_api_token }}"
    cluster_name: "K8s-{{ ansible_hostname }}"
    kubeconfig_path: "/etc/kubernetes/admin.conf"

  tasks:

    # --------------------------------------------------------
    # Ensure Kubernetes Python client exists on remote node
    # --------------------------------------------------------
    - name: Ensure python kubernetes client is installed
      pip:
        name: kubernetes
        executable: pip3

    # --------------------------------------------------------
    # Verify kubeconfig works on remote node
    # --------------------------------------------------------
    - name: Verify Kubernetes API connectivity
      command: kubectl --kubeconfig={{ kubeconfig_path }} get nodes
      register: kube_check
      changed_when: false

    - name: Debug cluster nodes
      debug:
        var: kube_check.stdout_lines

    # --------------------------------------------------------
    # Create Service Account
    # --------------------------------------------------------
    - name: Create Service Account for Morpheus
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition:
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: morpheus-admin
            namespace: kube-system

    # --------------------------------------------------------
    # Bind Cluster Admin Role
    # --------------------------------------------------------
    - name: Grant cluster-admin permissions
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRoleBinding
          metadata:
            name: morpheus-admin-binding
          subjects:
            - kind: ServiceAccount
              name: morpheus-admin
              namespace: kube-system
          roleRef:
            kind: ClusterRole
            name: cluster-admin
            apiGroup: rbac.authorization.k8s.io

    # --------------------------------------------------------
    # Create Service Account Token Secret
    # --------------------------------------------------------
    - name: Create long-lived API token secret
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: morpheus-admin-token
            namespace: kube-system
            annotations:
              kubernetes.io/service-account.name: morpheus-admin
          type: kubernetes.io/service-account-token

    # --------------------------------------------------------
    # Retrieve Token
    # --------------------------------------------------------
    - name: Retrieve service account token
      kubernetes.core.k8s_info:
        kubeconfig: "{{ kubeconfig_path }}"
        kind: Secret
        name: morpheus-admin-token
        namespace: kube-system
      register: sa_secret

    - name: Decode service account token
      set_fact:
        morpheus_service_token: "{{ sa_secret.resources[0].data.token | b64decode }}"

    # --------------------------------------------------------
    # Register Cluster in Morpheus
    # --------------------------------------------------------
    - name: Post Cluster Details to Morpheus API
      uri:
        url: "{{ morpheus_url }}/api/clusters"
        method: POST
        headers:
          Authorization: "BEARER {{ morpheus_api_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          cluster:
            name: "{{ cluster_name }}"
            type: "kubernetes"
            serviceUrl: "https://{{ ansible_host }}:6443"
            serviceToken: "{{ morpheus_service_token }}"
            apiProxy:
              verifySsl: false
        status_code: 201
