---
# ------------------------------------------------------------
# 1. Standard Kubespray Deployment
# ------------------------------------------------------------
- name: Deploy Kubernetes Cluster
  import_playbook: playbooks/cluster.yml


# ------------------------------------------------------------
# 2. Register Cluster with Morpheus
# ------------------------------------------------------------
- name: Register Cluster with Morpheus
  hosts: kube_control_plane[0]
  become: true
  gather_facts: true

  vars:
    morpheus_url: "https://98.85.233.250"
    morpheus_api_token: "{{ morpheus_api_token }}"
    cluster_name: "K8s-{{ ansible_hostname }}"
    local_kubeconfig: "/tmp/morpheus-kubeconfig"

  tasks:

    # --------------------------------------------------------
    # Read kubeconfig from control-plane
    # --------------------------------------------------------
    - name: Read kubeconfig from control plane
      slurp:
        src: /etc/kubernetes/admin.conf
      register: kubeconfig_raw

    # --------------------------------------------------------
    # Parse kubeconfig YAML
    # --------------------------------------------------------
    - name: Convert kubeconfig to YAML object
      set_fact:
        kubeconfig_yaml: "{{ kubeconfig_raw.content | b64decode | from_yaml }}"

    # --------------------------------------------------------
    # Replace API server endpoint with real node IP
    # --------------------------------------------------------
    - name: Update API server endpoint
      set_fact:
        kubeconfig_yaml: >-
          {{
            kubeconfig_yaml | combine({
              'clusters': [
                kubeconfig_yaml.clusters[0] | combine({
                  'cluster':
                    kubeconfig_yaml.clusters[0].cluster | combine({
                      'server': 'https://' ~ ansible_host ~ ':6443'
                    })
                })
              ]
            })
          }}

    # --------------------------------------------------------
    # Write kubeconfig inside AWX execution environment
    # --------------------------------------------------------
    - name: Write kubeconfig locally
      copy:
        content: "{{ kubeconfig_yaml | to_nice_yaml }}"
        dest: "{{ local_kubeconfig }}"
        mode: '0600'
      delegate_to: localhost

    # --------------------------------------------------------
    # Create Service Account
    # --------------------------------------------------------
    - name: Create Service Account for Morpheus
      kubernetes.core.k8s:
        kubeconfig: "{{ local_kubeconfig }}"
        state: present
        definition:
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: morpheus-admin
            namespace: kube-system
      delegate_to: localhost

    # --------------------------------------------------------
    # Create ClusterRoleBinding
    # --------------------------------------------------------
    - name: Grant cluster-admin permissions
      kubernetes.core.k8s:
        kubeconfig: "{{ local_kubeconfig }}"
        state: present
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRoleBinding
          metadata:
            name: morpheus-admin-binding
          subjects:
            - kind: ServiceAccount
              name: morpheus-admin
              namespace: kube-system
          roleRef:
            kind: ClusterRole
            name: cluster-admin
            apiGroup: rbac.authorization.k8s.io
      delegate_to: localhost

    # --------------------------------------------------------
    # Create Token Secret
    # --------------------------------------------------------
    - name: Create long-lived API token
      kubernetes.core.k8s:
        kubeconfig: "{{ local_kubeconfig }}"
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: morpheus-admin-token
            namespace: kube-system
            annotations:
              kubernetes.io/service-account.name: morpheus-admin
          type: kubernetes.io/service-account-token
      delegate_to: localhost

    # --------------------------------------------------------
    # Retrieve Token
    # --------------------------------------------------------
    - name: Retrieve token from cluster
      kubernetes.core.k8s_info:
        kubeconfig: "{{ local_kubeconfig }}"
        kind: Secret
        name: morpheus-admin-token
        namespace: kube-system
      register: sa_secret
      delegate_to: localhost

    - name: Decode service account token
      set_fact:
        morpheus_service_token: "{{ sa_secret.resources[0].data.token | b64decode }}"

    # --------------------------------------------------------
    # Register Cluster in Morpheus
    # --------------------------------------------------------
    - name: Post Cluster Details to Morpheus API
      uri:
        url: "{{ morpheus_url }}/api/clusters"
        method: POST
        headers:
          Authorization: "BEARER {{ morpheus_api_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          cluster:
            name: "{{ cluster_name }}"
            type: "kubernetes"
            serviceUrl: "https://{{ ansible_host }}:6443"
            serviceToken: "{{ morpheus_service_token }}"
            apiProxy:
              verifySsl: false
        status_code: 201
      delegate_to: localhost
      run_once: true
