---
# ------------------------------------------------------------
# 1. Standard Kubespray Deployment
# ------------------------------------------------------------
- name: Deploy Kubernetes Cluster
  import_playbook: playbooks/cluster.yml


# ------------------------------------------------------------
# 2. Register Cluster with Morpheus
# ------------------------------------------------------------
- name: Register Cluster with Morpheus
  hosts: kube_control_plane[0]
  become: true
  gather_facts: true

  vars:
    morpheus_url: "https://98.85.233.250"
    morpheus_api_token: "{{ morpheus_api_token }}"
    cluster_name: "K8s-{{ ansible_hostname }}"
    local_kubeconfig: "/tmp/morpheus-kubeconfig"

  tasks:

    # --------------------------------------------------------
    # 1. Read kubeconfig from control-plane node
    # --------------------------------------------------------
    - name: Read kubeconfig from control plane
      slurp:
        src: /etc/kubernetes/admin.conf
      register: kubeconfig_raw

    # --------------------------------------------------------
    # 2. Fix localhost server endpoint if needed
    # --------------------------------------------------------
    - name: Adjust kubeconfig server address
      set_fact:
        fixed_kubeconfig: >-
          {{
            kubeconfig_raw.content | b64decode
            | regex_replace('https://127.0.0.1:6443',
                            'https://' ~ ansible_host ~ ':6443')
            | regex_replace('https://localhost:6443',
                            'https://' ~ ansible_host ~ ':6443')
          }}

    # --------------------------------------------------------
    # 3. Write kubeconfig inside AWX execution environment
    # --------------------------------------------------------
    - name: Write kubeconfig locally inside AWX
      copy:
        content: "{{ fixed_kubeconfig }}"
        dest: "{{ local_kubeconfig }}"
        mode: '0600'
      delegate_to: localhost

    # --------------------------------------------------------
    # 4. Create Service Account
    # --------------------------------------------------------
    - name: Create Service Account for Morpheus
      kubernetes.core.k8s:
        kubeconfig: "{{ local_kubeconfig }}"
        state: present
        definition:
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: morpheus-admin
            namespace: kube-system
      delegate_to: localhost

    # --------------------------------------------------------
    # 5. Create ClusterRoleBinding
    # --------------------------------------------------------
    - name: Grant cluster-admin permissions
      kubernetes.core.k8s:
        kubeconfig: "{{ local_kubeconfig }}"
        state: present
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRoleBinding
          metadata:
            name: morpheus-admin-binding
          subjects:
            - kind: ServiceAccount
              name: morpheus-admin
              namespace: kube-system
          roleRef:
            kind: ClusterRole
            name: cluster-admin
            apiGroup: rbac.authorization.k8s.io
      delegate_to: localhost

    # --------------------------------------------------------
    # 6. Create Token Secret
    # --------------------------------------------------------
    - name: Create long-lived API token secret
      kubernetes.core.k8s:
        kubeconfig: "{{ local_kubeconfig }}"
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: morpheus-admin-token
            namespace: kube-system
            annotations:
              kubernetes.io/service-account.name: morpheus-admin
          type: kubernetes.io/service-account-token
      delegate_to: localhost

    # --------------------------------------------------------
    # 7. Retrieve Token
    # --------------------------------------------------------
    - name: Retrieve service account token
      kubernetes.core.k8s_info:
        kubeconfig: "{{ local_kubeconfig }}"
        kind: Secret
        name: morpheus-admin-token
        namespace: kube-system
      register: sa_secret
      delegate_to: localhost

    - name: Decode service account token
      set_fact:
        morpheus_service_token: "{{ sa_secret.resources[0].data.token | b64decode }}"

    # --------------------------------------------------------
    # 8. Register Cluster in Morpheus
    # --------------------------------------------------------
    - name: Post Cluster Details to Morpheus API
      uri:
        url: "{{ morpheus_url }}/api/clusters"
        method: POST
        headers:
          Authorization: "BEARER {{ morpheus_api_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          cluster:
            name: "{{ cluster_name }}"
            type: "kubernetes"
            serviceUrl: "https://{{ ansible_host }}:6443"
            serviceToken: "{{ morpheus_service_token }}"
            apiProxy:
              verifySsl: false
        status_code: 201
      delegate_to: localhost
      run_once: true
