- name: 2. Register Cluster with Morpheus
  hosts: kube_control_plane[0]
  become: true  # Necessary for the 'slurp' task on vm-1
  vars:
    morpheus_url: "https://98.85.233.250"
    morpheus_api_token: "{{ morpheus_api_token }}"
    cluster_name: "K8s-{{ ansible_hostname }}"
    k8s_api_host: "https://{{ ansible_host }}:6443"

  tasks:
    - name: Read kubeconfig from vm-1
      ansible.builtin.slurp:
        src: "/etc/kubernetes/admin.conf"
      register: remote_kubeconfig

    - name: Create Service Account for Morpheus
      kubernetes.core.k8s:
        host: "{{ k8s_api_host }}"
        kubeconfig: "{{ remote_kubeconfig.content | b64decode | from_yaml }}"
        validate_certs: false
        definition:
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: morpheus-admin
            namespace: kube-system
      delegate_to: localhost
      become: false  # Don't use sudo on the AWX container

    - name: Grant cluster-admin permissions
      kubernetes.core.k8s:
        host: "{{ k8s_api_host }}"
        kubeconfig: "{{ remote_kubeconfig.content | b64decode | from_yaml }}"
        validate_certs: false
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRoleBinding
          metadata:
            name: morpheus-admin-binding
          subjects:
          - kind: ServiceAccount
            name: morpheus-admin
            namespace: kube-system
          roleRef:
            kind: ClusterRole
            name: cluster-admin
            apiGroup: rbac.authorization.k8s.io
      delegate_to: localhost
      become: false

    - name: Create long-lived API token secret
      kubernetes.core.k8s:
        host: "{{ k8s_api_host }}"
        kubeconfig: "{{ remote_kubeconfig.content | b64decode | from_yaml }}"
        validate_certs: false
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: morpheus-admin-token
            namespace: kube-system
            annotations:
              kubernetes.io/service-account.name: morpheus-admin
          type: kubernetes.io/service-account-token
      delegate_to: localhost
      become: false

    - name: Retrieve the Service Account token
      kubernetes.core.k8s_info:
        host: "{{ k8s_api_host }}"
        kubeconfig: "{{ remote_kubeconfig.content | b64decode | from_yaml }}"
        validate_certs: false
        kind: Secret
        name: morpheus-admin-token
        namespace: kube-system
      register: sa_secret
      delegate_to: localhost
      become: false
      no_log: true

    - name: Post Cluster Details to Morpheus API
      uri:
        url: "{{ morpheus_url }}/api/clusters"
        method: POST
        headers:
          Authorization: "BEARER {{ morpheus_api_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          cluster:
            name: "{{ cluster_name }}"
          # 1. Try 'externalKubernetes' instead of 'kubernetes'
            type: "kubernetes" 
            # 2. Use ID instead of name for Site
            cloud:
              id: 1 # <--- Find this ID in Infrastructure > Clouds URL
            # 3. Use ID instead of name for Layout
            layout:
              name: "Kubernetes Cluster" # <--- Find this ID in Library > Cluster Layouts URL
            # 4. Use ID for Group
            group:
              id: 1  # <--- Find this ID in Infrastructure > Groups URL
            serviceUrl: "{{ k8s_api_host }}"
            serviceToken: "{{ sa_secret.resources[0].data.token | b64decode }}"
            apiProxy: { verifySsl: false }
            enabled: true
        status_code: 201
        validate_certs: false
      delegate_to: localhost
      become: false
      register: morpheus_response

    - name: Success Message
      debug:
        msg: "Cluster successfully registered! Morpheus ID: {{ morpheus_response.json.cluster.id }}"
      when: morpheus_response.status == 201
      become: false
