collections:
  - name: netbox.netbox      # For NetBox inventory
    version: "3.22.0"
  - name: community.general  # For Kubespray
    version: "8.0.0"
  - name: ansible.utils
    version: ">=2.10.3"
  - name: ansible.posix
    version: ">=1.5.4"
  - name: ansible.utils
    version: ">=4.1.0"
  - name: kubernetes.core
    version: ">=3.1.0"
  - name: community.crypto
    version: ">=2.0.0"
